### ISSUE TITLE
build error: com.networknt.rpc.Handler getStatus method change incompatible 

### ISSUE THREAD

**Issue by chenyan71** [networknt/light-config-server#14]
build error. 

com.networknt.rpc.Handler getStatue() method changed. 

in the InitializeServer handler class, still using old method:

getStatus(CONFIG_SERVER_INITIALIZED)

**Comment by stevehu** [comment]
Just realized that we haven't put the light-config-server into the build-test-all light-bot auto build yet. I have opened an issue to address it. 

https://github.com/networknt/light-config-test/issues/93
